service: droid

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    DROID_TABLE: "${self:service}-${opt:stage, self:provider.stage}-droids"


package:
  include:
    - dao/droid-dao.js

functions:
  create:
    handler: admin/create.create
    events:
      - http:
          path: droids
          method: post
          cors: true
  delete:
    handler: admin/delete.delete
    events:
      - http:
          path: droids/{id}
          method: delete
          cors: true
  get:
    handler: admin/get.get
    events:
      - http:
          path: droids/{id}
          method: get
          cors: true
  list:
    handler: admin/list.list
    events:
      - http:
          path: droids
          method: get
          cors: true
  update:
    handler: admin/update.update
    events:
      - http:
          path: droids/{id}
          method: put
          cors: true

